export const DEVICE = 'DEVICE'
export const ORIENTATION = 'ORIENTATION'

export const SHOWFOOTER = 'SHOWFOOTER'
export const HIDEFOOTER = 'HIDEFOOTER'

export const SHOWWRAPPER = 'SHOWWRAPPER'
export const HIDEWRAPPER = 'HIDEWRAPPER'

export const INITDISMOUNT = 'INITDISMOUNT'
export const EXITDISMOUNT = 'EXITDISMOUNT'

export const POSTGAME = 'POSTGAME'

export const GETSCOREBOARD = 'GETSCOREBOARD'
export const ADDSCORE = 'ADDSCORE'
export const CLEARSCORE = 'CLEARSCORE'
