export const DEVICE = 'DEVICE'
export const ORIENTATION = 'ORIENTATION'

export const STOREPLAYER = 'STOREPLAYER'
export const RESETPLAYER = 'RESETPLAYER'

export const SHOWFOOTER = 'SHOWFOOTER'
export const HIDEFOOTER = 'HIDEFOOTER'

export const SHOWWRAPPER = 'SHOWWRAPPER'
export const HIDEWRAPPER = 'HIDEWRAPPER'

export const INITDISMOUNT = 'INITDISMOUNT'
export const EXITDISMOUNT = 'EXITDISMOUNT'

export const GETSCOREBOARD = 'GETSCOREBOARD'
