export const DEVICE = 'DEVICE'
export const ORIENTATION = 'ORIENTATION'

export const SHOWFOOTER = 'SHOWFOOTER'
export const HIDEFOOTER = 'HIDEFOOTER'

export const SHOWWRAPPER = 'SHOWWRAPPER'
export const HIDEWRAPPER = 'HIDEWRAPPER'

export const INITDISMOUNT = 'INITDISMOUNT'
export const EXITDISMOUNT = 'EXITDISMOUNT'

export const GETSCOREBOARD = 'GETSCOREBOARD'

export const CLEARSCORE = 'CLEARSCORE'
export const STORESCORE = 'STORESCORE'
export const SUBMITSCORE = 'SUBMITSCORE'

export const POSTGAME = 'POSTGAME'
